server:
  port: 9091
spring:
  application:
    name: YunApiGateWay
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:9090
          predicates:
            - Path=/api/**

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

dubbo:
  protocol:
    name: dubbo
    port: 20881
  # 注册中心地址
  registry:
    address: nacos://localhost:8848
  application:
    qos-enable: false
  consumer:
    check: false
